# Generated by Django 5.2.14 on 2026-05-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_clicklog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clicklog",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="clicklog",
            name="user_browser",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="clicklog",
            name="user_device",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="clicklog",
            name="user_os",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
